# Generated by Django 3.0.7 on 2020-06-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_url',
            field=models.CharField(help_text='Copy the url link of the song', max_length=1000, unique='TRUE'),
        ),
    ]
