# Generated by Django 3.0.7 on 2020-06-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200617_0647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
